<?php

// $Id$


/**
 * @file
 * Configuration module for islandora_solr_search.module
 */


/**
 * Implementation of hook_alter_form.
 * Adds this module's configuration options to islandora_solr_search's configuration page.
 
function esdora_solr_config_form_islandora_solr_admin_settings_alter(&$form, &$form_state) {
  $module   = 'esdora_solr_config';
  $file     = 'EsdoraSolrResults.inc';
  $class    = 'EsdoraSolrResults';
  $method   = 'displayResults';
  $config_options = $form['islandora_solr_config_options']['#options'];
  $config_options["${module}~${file}~${class}~${method}"] = 'Esdora';
  $form['islandora_solr_config_options']['#options'] = $config_options;
}
 * 
 */


/**
 * Implements hook_islandora_solr_primary_display()
 */
function esdora_solr_config_islandora_solr_primary_display() {
  return array(
    'esdora_table' => array(
      'name' => t('Esdora'),
      'module' => 'Esdora_solr_config',
      'file' => 'EsdoraSolrResults.inc',
      'class' => "EsdoraSolrResults",
      'function' => "displayResults",
      'description' => t("A simple tabular output"),
    ),
  );
}

/**
 * Implementation of hook_help()
 */
function esdora_co_solr_config_help($path, $arg) {

  switch ($path) {
    case 'admin/help#islandora_solr_config':
      return t("When 'Sample Solr Configuration Settings' is selected from the configuration drop-down in the<br />
        !page the following settings will be used.
        <ul>
        <li>Module - islandora_solr_config</l1>
        <li>File - IslandoraSolrResultsTable.inc</l1>
        <li>Class - IslandoraSolrResultsTable</l1>
        <li>Method - displayResults</l1>
        </ul>
        ", array('!page' => l("Islandora_solr_search configuration page", 'admin/settings/islandora_solr_search'),)


      );
  }
}

